export const cubeDimension = 1.5;
export const textureResourcePath = './bg.jpg';
export const numberOfBoxes = Math.min(150, Math.round( 100 * (window.innerWidth * window.innerHeight / 1000000)));
export const cameraFieldOfView = 75 // degrees
export const cameraAspectRatio = window.innerWidth / window.innerHeight;
export const cameraBorderFront = 0.1; 
export const cameraBorderRear = 100; 
export const cameraPositionXAxis = 0;
export const cameraPositionYAxis = -5;
export const cameraPositionZAxis = 40;
export const VelocityXAxis = 0.2;
export const VelocityYAxis = 0.2;
export const VelocityZAxis = 0.2;
export const cubeRotationXAxis = 0.05;
export const cubeRotationYAxis = 0.02;
export const cubeRotationZAxis = 0.05;
export const halfLineLength = 1000;
export const cubePositionAvgDispersion = 20;
